{% set name = "pymoo" %}
{% set version = "0.6.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymoo-{{ version }}.tar.gz
  sha256: 56de712dbf71017fb69720360242d3bd7964794e82b95d934a1b772ae83ce71d

build:
  number: 1

  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - autograd >=1.4
    - cma ==3.2.2
    - matplotlib-base >=3
    - numpy >=1.15
    - python
    - scipy >=1.1
    - dill
    - alive-progress
    - Deprecated
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymoo
    - pymoo.algorithms
  commands:
    - pip check
    - python -c "from pymoo.util.function_loader import is_compiled; exit(is_compiled()!=True)"
  requires:
    - pip

about:
  home: https://pymoo.org
  summary: Multi-Objective Optimization in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyrilpic
    - d-cunningham
    - mxr-conda
