{% set name = "pymoo" %}
{% set version = "0.6.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymoo-{{ version }}.tar.gz
  sha256: 648cd3d5901d45ddf36d4a352eb7054933e29a275a18d7763138d220849d8485

build:
  number: 2

  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - autograd >=1.4
    - cma ==3.2.2
    - matplotlib-base >=3
    - numpy >=1.15
    - python
    - scipy >=1.1
    - dill
    - alive-progress
    - Deprecated

test:
  imports:
    - pymoo
    - pymoo.algorithms
  commands:
    - pip check
    - python -c "from pymoo.util.function_loader import is_compiled; exit(is_compiled()!=True)"
  requires:
    - pip

about:
  home: https://pymoo.org
  summary: Multi-Objective Optimization in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyrilpic
    - d-cunningham
    - mxr-conda
