{% set name = "pymoo" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymoo-{{ version }}.tar.gz
  sha256: 2fbca1716f6b45e430197ce4ce2210070fd3b6b9ec6b17bb25d98486115272c2

build:
  number: 3
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - autograd >=1.3
    - cma ==2.7
    - matplotlib-base >=3
    - numpy >=1.15
    - python
    - scipy >=1.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pymoo
    - pymoo.algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pymoo.org
  summary: Multi-Objective Optimization in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cyrilpic
    - d-cunningham
    - mxr-conda
